In [1]:
import gym
import numpy as np
import time
from IPython.display import clear_output
import random

In [2]:
env=gym.make("MountainCar-v0")


learning=0.1
discount=0.95
episodes=25000
showEvery=2000

DISCRETE_OS_SIZE=[20,20]
discrete_os_win_size=(env.observation_space.high-env.observation_space.low)/DISCRETE_OS_SIZE
epsilon=0.5
start=1
end=episodes//2
q_table=np.random.uniform(low=-2,high=0,size=(DISCRETE_OS_SIZE + [env.action_space.n]))

def getDiscrete(state):
    discrete=(state-env.observation_space.low)/discrete_os_win_size
    return tuple(discrete.astype(np.int))
for episode in range(episodes):
    if episode %showEvery ==0:
        render=True 
    else:
        render=False
        
    discrete=getDiscrete(env.reset())

    done = False
    while not done:
        action =np.argmax(q_table[discrete])
        new_state,reward,done,_=env.step(action)
        new_discrete_state= getDiscrete(new_state)
        if render:
            env.render()
        if not done:
            max_future_q = np.max(q_table[new_discrete_state])
            current_q=q_table[discrete + (action, )]

            new_q=(1-learning)*current_q + learning * (reward + discount*max_future_q)

            q_table[discrete + (action, )]=new_q #update the new_q value 
        elif new_state[0]>= env.goal_position:
            print(f"we made it {episode}")
            q_table[discrete+(action,)]=0

    env.close()

In [10]:
import gym
import numpy as np

env = gym.make("MountainCar-v0")
env.reset()

DISCRETE_OS_SIZE = [20, 20]
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_OS_SIZE

q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))
print(q_table)
'''done = False

while not done:
    action = 2
    new_state, reward, done, _ = env.step(action)
    print(reward, new_state)
    env.render()'''
    #new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

[[[-0.9988448  -0.94586043 -0.17906415]
  [-0.95229149 -1.38362095 -1.31009427]
  [-1.19137494 -0.45818644 -0.07202258]
  ...
  [-0.42691305 -1.82038544 -0.91437963]
  [-1.43886407 -1.53059122 -1.8198212 ]
  [-1.12517849 -1.84950683 -0.00572236]]

 [[-0.13042897 -0.61892744 -0.29279178]
  [-0.46040349 -1.30895009 -1.19001531]
  [-0.61045359 -0.59946788 -1.60782735]
  ...
  [-1.5091164  -0.59606213 -1.77394296]
  [-0.94808909 -0.53090884 -0.25382418]
  [-0.5438734  -1.12710211 -1.85396451]]

 [[-1.68623802 -0.52164232 -1.12013273]
  [-1.51479983 -1.33030875 -1.40534708]
  [-1.40211857 -0.77551763 -1.83964863]
  ...
  [-1.35097281 -0.05085253 -1.05321864]
  [-1.24442862 -0.61586223 -1.80760536]
  [-1.9103318  -0.89241316 -0.69695448]]

 ...

 [[-0.99307418 -1.38218159 -0.8327042 ]
  [-0.37905246 -0.46522924 -1.63646103]
  [-0.80277049 -0.8883301  -1.75283999]
  ...
  [-0.87357753 -1.71255412 -0.15476057]
  [-0.18025102 -1.30050149 -0.30713253]
  [-1.25749112 -0.57177037 -0.95832142]]

 [

'done = False\n\nwhile not done:\n    action = 2\n    new_state, reward, done, _ = env.step(action)\n    print(reward, new_state)\n    env.render()'

In [3]:
import gym
import numpy as np

env = gym.make("MountainCar-v0")

LEARNING_RATE = 0.1

DISCOUNT = 0.95
EPISODES = 25000
SHOW_EVERY = 3000

DISCRETE_OS_SIZE = [20, 20]
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_OS_SIZE

# Exploration settings
epsilon = 1  # not a constant, qoing to be decayed
START_EPSILON_DECAYING = 1
END_EPSILON_DECAYING = EPISODES//2
epsilon_decay_value = epsilon/(END_EPSILON_DECAYING - START_EPSILON_DECAYING)


q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))


def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(np.int))  # we use this tuple to look up the 3 Q values for the available actions in the q-table


for episode in range(EPISODES):
    discrete_state = get_discrete_state(env.reset())
    done = False

    if episode % SHOW_EVERY == 0:
        render = True
        print(episode)
    else:
        render = False

    while not done:

        if np.random.random() > epsilon:
            # Get action from Q table
            action = np.argmax(q_table[discrete_state])
        else:
            # Get random action
            action = np.random.randint(0, env.action_space.n)


        new_state, reward, done, _ = env.step(action)

        new_discrete_state = get_discrete_state(new_state)

        if episode % SHOW_EVERY == 0:
            env.render()
        #new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

        # If simulation did not end yet after last step - update Q table
        if not done:

            # Maximum possible Q value in next step (for new state)
            max_future_q = np.max(q_table[new_discrete_state])

            # Current Q value (for current state and performed action)
            current_q = q_table[discrete_state + (action,)]

            # And here's our equation for a new Q value for current state and action
            new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

            # Update Q table with new Q value
            q_table[discrete_state + (action,)] = new_q


        # Simulation ended (for any reson) - if goal position is achived - update Q value with reward directly
        elif new_state[0] >= env.goal_position:
            #q_table[discrete_state + (action,)] = reward
            q_table[discrete_state + (action,)] = 0

        discrete_state = new_discrete_state

    # Decaying is being done every episode if episode number is within decaying range
    if END_EPSILON_DECAYING >= episode >= START_EPSILON_DECAYING:
        epsilon -= epsilon_decay_value


env.close()

0
3000
6000
9000
12000
15000
18000
21000
24000


In [3]:
env=gym.make("FrozenLake-v0")
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01


In [9]:
rewards_all_episodes=[]
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    # initialize new episode params1
    
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        # Take new action
        # Update Q-table
        # Set new state
        # Add new reward        

    # Exploration rate decay   
    # Add current episode reward to total rewards list
    
# Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode += reward 
        if done == True: 
            break
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
    # Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.11600000000000009
2000 :  0.4100000000000003
3000 :  0.6050000000000004
4000 :  0.6560000000000005
5000 :  0.6510000000000005
6000 :  0.6210000000000004
7000 :  0.6410000000000005
8000 :  0.6680000000000005
9000 :  0.6590000000000005
10000 :  0.6430000000000005


********Q-table********

[[0.54722462 0.38454463 0.42698364 0.3700479 ]
 [0.33564718 0.07893675 0.09180514 0.06392238]
 [0.26155148 0.07145738 0.0608004  0.05538016]
 [0.04438513 0.         0.         0.        ]
 [0.55431149 0.39435342 0.28402123 0.28693299]
 [0.         0.         0.         0.        ]
 [0.10910964 0.10738938 0.23728786 0.05701324]
 [0.         0.         0.         0.        ]
 [0.32447128 0.3993255  0.40275511 0.57962764]
 [0.54048705 0.62158393 0.35465976 0.36655775]
 [0.52374958 0.30015191 0.27664144 0.20447185]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49278248 0.47895931 0.74892453 0

In [4]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table
env=gym.make("FrozenLake-v0")
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    # initialize new episode params

    for step in range(max_steps_per_episode):  
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        # Show current state of environment on screen
        # Choose action with highest Q-value for current state       
        # Take new action
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(1)
                # Agent reached the goal and won episode
            else:
                print("****You fell through a hole!****")# Agent stepped in a hole and lost episode            
                time.sleep(1)
            clear_output(wait=True)
            break
            # Set new state
        state=new_state
        
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
